### ISSUE TITLE
Compile instructions

### ISSUE THREAD

**Issue by TheGreatestJannet** [hivecom/pokebot#46]
Is there any instructions for compiling the bot as I would like to run it on a raspberry pi with an ARM processor.

**Comment by Jokler** [comment]
To compile it you need rust and the GStreamer development libraries, at that point it is just a simple `cargo build --release` and the binary will be created under `target/release/pokebot`.
For rust I would recommend installing `rustup` and then running `rustup default stable`.
If you are on Ubuntu or a distribution based on it this should help you with the compile time dependencies:
https://github.com/Mavulp/pokebot/blob/3d6688e6cb45bc1c8ec85abebfa57637e071d5ac/.github/workflows/create-release.yml#L18

I would recommend against compiling it on the raspberry directly because that would take a long time.

If you want to cross-compile from another system you can install the ARM version of GCC which should be called `gcc-4.7-multilib-arm-linux-gnueabihf`on Ubuntu I believe.
You can then set up a build target by running `rustup target add armv7-unknown-linux-gnueabihf` and adding the following to `~/.cargo/config`:
```
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
```

If everything went well you should now be able to run `cargo build --target=armv7-unknown-linux-gnueabihf` to build an ARM binary. 

Once you get it to work I will add this to the readme.

**Comment by TheGreatestJannet** [comment]
Thanks I have installed gstreamer development libraries, cargo and then cloned the repo. I then ran cargo build --release  and got the following error:
```
error: failed to parse lock file at: /home/user/pokebot/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
```

**Comment by Jokler** [comment]
I will look into it, for now you can try to just delete `Cargo.lock` and see if it works.

Edit: Just in case, are you on the latest rust version? That's the only one I am currently testing with.

**Comment by TheGreatestJannet** [comment]
I deleted the file and tried compiling and got the following error:
 ```
error[E0432]: unresolved import `core::task::Context`                                                          
  --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:21:18  
   | 
21 | use core::task::{Context, Poll};                                                                          
   |                  ^^^^^^^ no `Context` in `task`                                                    
     
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:17:1   
   | 
17 | extern crate alloc;                                                                                       
   | ^^^^^^^^^^^^^^^^^^^                                                                                
     
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:21:27  
   | 
21 | use core::task::{Context, Poll};
   |                           ^^^^                                                                     
                            
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:66:66
   |                        
66 |     fn poll_ready(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>>;           
   |                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     
                        
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:101:66
    |                           
101 |     fn poll_flush(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>>;          
    |                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
                              
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:114:66
    |                              
114 |     fn poll_close(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>>;          
    |                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
                               
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:120:70
    |                      
120 |     fn poll_ready(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {     
    |                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                       
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:128:70
    |                                
128 |     fn poll_flush(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {     
    |                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                           
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:132:70
    |                           
132 |     fn poll_close(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {     
    |                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:144:66
    |
144 |     fn poll_ready(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {                                         
    |                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
     
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:152:66
    |
152 |     fn poll_flush(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {         
    |                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
     
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:156:66
   |     fn poll_close(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {         
    |                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
                            
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:169:69
    |                   
169 |         fn poll_ready(self: Pin<&mut Self>, _: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {      
    |                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
                                
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:170:13
    |                         
170 |             Poll::Ready(Ok(()))                                                                          
    |             ^^^^^^^^^^^                                                                           
                                   
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:179:69
    |                          
179 |         fn poll_flush(self: Pin<&mut Self>, _: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {      
    |                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
                           
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:180:13
    |                  
180 |             Poll::Ready(Ok(()))                                                                          
    |             ^^^^^^^^^^^                                                                           
                                     
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:183:69
    |                      
183 |         fn poll_close(self: Pin<&mut Self>, _: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {      
    |                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
                                
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:184:13
    |
184 |             Poll::Ready(Ok(()))                                                                          
    |             ^^^^^^^^^^^                                                                           
     
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)                                
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:191:69
    |
191 |         fn poll_ready(self: Pin<&mut Self>, _: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {      
    |                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
     
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:192:13
    |
192 |             Poll::Ready(Ok(()))                                                                          
    |             ^^^^^^^^^^^
    error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:201:69
    |                       
201 |         fn poll_flush(self: Pin<&mut Self>, _: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {      
    |                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
                        
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:202:13
    |                           
202 |             Poll::Ready(Ok(()))                                                                          
    |             ^^^^^^^^^^^                                                                           
                              
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:205:69
    |                              
205 |         fn poll_close(self: Pin<&mut Self>, _: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {      
    |                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
                               
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:206:13
    |                      
206 |             Poll::Ready(Ok(()))                                                                          
    |             ^^^^^^^^^^^                                                                           
                       
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:213:74
    |                                
213 |         fn poll_ready(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> { 
    |                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                           
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:221:74
    |                           
221 |         fn poll_flush(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> { 
    |                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     
error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.4/src/lib.rs:225:74
    |
225 |         fn poll_close(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {                                 
    |                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     
error: aborting due to 27 previous errors                                                                      
                                                                                                        
Some errors occurred: E0432, E0658.
For more information about an error, try `rustc --explain E0432`.                                              
error: Could not compile `futures-sink`.                                                                
warning: build failed, waiting for other jobs to finish...
error: build failed
```
I am using the version in the debian repo:
```
Package: rustc
Version: 1.34.2+dfsg1-1+rpi1
```

**Comment by Jokler** [comment]
That version is definitely too old, we are using features from at least 1.39.0.
The easiest way to get the latest version would be rustup.

**Comment by TheGreatestJannet** [comment]
Thank you I will download a newer version and report back

**Comment by TheGreatestJannet** [comment]
It has compiled successfully however if I run ./pokebot I get this error:
```
./pokebot 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Log4rs(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/main.rs:73:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by TheGreatestJannet** [comment]
With RUST_BACKTRACE=1 I get:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Log4rs(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/main.rs:73:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1199
  14: pokebot::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  17: std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  19: std::panicking::try
             at src/libstd/panicking.rs:281
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  22: main
  23: __libc_start_main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Jokler** [comment]
Make sure that you copy the `log4rs.yml` over and also create a `config.toml`, you can have a look at the [example config](https://github.com/Mavulp/pokebot/blob/e71c6356f53538a20b711510e5d558d969474ad5/config.toml.example) for that.

**Comment by TheGreatestJannet** [comment]
Thanks I have two questions: if I want to update the bot do I just run `git pull` and then `cargo build --release` again or do I need to delete the folder and compile from fresh again?
Secondly how do I get an ID and what are `counter` and `max_counter` in the config? I have tried running `./pokebot -g 1` and I get: `Error: invalid value: string "", expected a P256 private ecc key for key id.key at line 17 column 7`

**Comment by Jokler** [comment]
You should not have to delete any build artifacts, keeping the files will make future compilations faster.

Make sure you are on the latest commit because I improved that part in #47 earlier and then just delete all the id related stuff from your config file like I did [here](https://github.com/Mavulp/pokebot/pull/47/files#diff-c18ae2d8b23f1968bca15e8e349dbbf3L14).
After that you should be able to use `pokebot -g 1` though that would only allow one music bot to connect at once so you might want to increase that number if you need more.

You don't have to know what `counter` and `max_counter` are, those should be generated as part of the ids and are needed for the security level feature of TeamSpeak.

**Comment by TheGreatestJannet** [comment]
Thank you that worked perfectly however my server has a security level of 23. How would I generate one of level at least 23?

**Comment by Jokler** [comment]
There is currently no way of increasing it in the bot, I can add add a flag to do that if that would help.

**Comment by TheGreatestJannet** [comment]
Yes please that would be very helpful and would allow people to connect to servers with higher security levels.

**Comment by TheGreatestJannet** [comment]
After connecting I get a couple errors:
```
ERRO Command stream exited with error (FutureCanceled(Canceled))
Unknown message channellistfinished
Unknown message notifychannelgrouplist
Unknown message notifyclientneededpermissions
17:44:35.299 ERROR tokio-runtime-worker-1[3046104736] src/teamspeak/mod.rs:193 - Failed to change description: PermissionsClientInsufficient
```
Also how do I interact with the bot and get it to play music? If I private message the bot I get: `Unknown message notifyclientchatcomposing`
Looking though the code it seems that `Play` and `Search` are the commands you need to use but they don't seem to do anything (probably because I'm doing it wrong!).

Edit: I have discovered it is by poking the bot. However when I do that it seems to give an error and the main bot as well as the secondary bot that is spawned both timout: 
```
17:52:25.078 INFO tokio-runtime-worker-0[3054493344] src/audio_player.rs:89 - Creating audio player
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: GStreamerError(BoolError { message: "Failed to create element from factory name", filename: "/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/gstreamer-0.15.0/src/auto/element_factory.rs", function: "gstreamer::auto::element_factory", line: 184 })', src/bot/music.rs:111:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/mod.rs:269:9
  Mar 22 17:52:25.080 INFO Changed state, new: Disconnecting, old: Normal
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: SpawnError { is_shutdown: true }', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.9/src/global.rs:172:5
```

**Comment by Jokler** [comment]
#47 should resolve your security level issue, to play music the bot requires some additional runtime GStreamer libraries.
I believe the one you are looking for is called `gstreamer1.0-plugins-good`.

**Comment by Jokler** [comment]
It tries to change the description to show the name of what's currently playing there, so if you want it to be able to do that you would have to give it permission to change it's own description.

**Comment by TheGreatestJannet** [comment]
Thank you so can I choose the security level I want when I run the -g command? Also I have installed gstreamer1.0-plugins-good. This has solved the issue and the bot now joins the channel correctly however doesn't play any music. The console doesn't seem to show anything useful either: 
```
18:13:15.986 INFO tokio-runtime-worker-1[3047153312] src/audio_player.rs:89 - Creating audio player
18:13:16.044 INFO tokio-runtime-worker-1[3047153312] src/audio_player.rs:208 - Setting volume: 0.5 -> -15.05149978319906 dB                                                                                                                  
18:13:16.046 INFO tokio-runtime-worker-1[3047153312] src/bot/music.rs:265 - Setting TeamsSpeak nickname to 🎵 MusicBot (50%)                                                                                                                 
18:13:16.046 DEBUG gstreamer polling[3009363616] src/audio_player.rs:334 - Polling GStreamer
18:13:16.047 DEBUG gstreamer polling[3009363616] src/audio_player.rs:365 - Pipeline transitioned from Null to Ready, with VoidPending pending
```
then the new bot that joined the channel seems to freeze and stop responding to commands.

**Comment by Jokler** [comment]
After generating the identities you would run it again with `pokebot -w 32` to upgrade the security level.

I am not sure why it freezes for you, could you maybe make a new issue and explain exactly what you did? Then you could close this issue once you don't have any problems related to the compilation anymore.

**Comment by TheGreatestJannet** [comment]
Thank you I'll close this issue and open another.

**Comment by Jokler** [comment]
This issue should actually stay open until I have actually added all of this to the readme, my bad.
